export const color1 = '#bf1e2e'; //reddish brown
export const color2 = '#f7941d';
export const color3 = '#1976d2'; //default blue
export const color4 = '#ff7b00'; // orange
export const color5 = '#bd150b'; //red
export const MedantaOrange = '#f04e30';
export const color = color3;
export const HomeDoctorList = color1;
export const DoctorDetails = color1;
export const ContactColor = color3;
export const Font = 'montserrat';
export const HName = 'SCI/';
